; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28106.4 

	TITLE	C:\Users\t_bal\source\repos\PonyMenu\PonyMenu\Debug\moc\moc_PonyMenu.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG141295 DB	'C:\qt\5.11.3\msvc2015\include\QtCore\qmetatype.h', 00H
	ORG $+7
$SG141296 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG141297 DB	'qRegisterNormalizedMetaType', 00H
$SG141634 DB	'C:\qt\5.11.3\msvc2015\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG141635 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG141636 DB	'qRegisterNormalizedMetaType', 00H
$SG141973 DB	'C:\qt\5.11.3\msvc2015\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG141974 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG141975 DB	'qRegisterNormalizedMetaType', 00H
$SG142803 DB	'C:\qt\5.11.3\msvc2015\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG142804 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG142805 DB	'qRegisterNormalizedMetaType', 00H
$SG143152 DB	'invalid argument', 00H
	ORG $+3
$SG143153 DB	'%s', 00H
	ORG $+1
?qt_meta_stringdata_PonyMenu@@3Uqt_meta_stringdata_PonyMenu_t@@B DD 0ffffffffH ; qt_meta_stringdata_PonyMenu
	DD	08H
	DD	00H
	DD	010H
	DB	050H
	DB	06fH
	DB	06eH
	DB	079H
	DB	04dH
	DB	065H
	DB	06eH
	DB	075H
	DB	00H
	ORG $+3
$SG143154 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
$SG143155 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H
	DB	'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H, '\'
	DB	00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H
	DB	'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H, '4'
	DB	00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H, '8', 00H
	DB	'1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c'
	DB	00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H
	DB	'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H, 00H
	DB	00H
$SG143156 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG143157 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG143266 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xlocale', 00H
?qt_meta_data_PonyMenu@@3QBIB DD 07H			; qt_meta_data_PonyMenu
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
$SG138410 DB	'C:\qt\5.11.3\msvc2015\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG138411 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG138412 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@PonyMenu@@UBEPBUQMetaObject@@XZ	; PonyMenu::metaObject
PUBLIC	?qt_metacast@PonyMenu@@UAEPAXPBD@Z		; PonyMenu::qt_metacast
PUBLIC	?qt_metacall@PonyMenu@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; PonyMenu::qt_metacall
PUBLIC	?qt_static_metacall@PonyMenu@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; PonyMenu::qt_static_metacall
PUBLIC	?staticMetaObject@PonyMenu@@2UQMetaObject@@B	; PonyMenu::staticMetaObject
EXTRN	_strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@PonyMenu@@2UQMetaObject@@B DB 018H DUP (?) ; PonyMenu::staticMetaObject
_BSS	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@PonyMenu@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@PonyMenu@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@PonyMenu@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@PonyMenu@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@PonyMenu@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'PonyMenu::staticMetaObject'', COMDAT
; File C:\Users\t_bal\source\repos\PonyMenu\PonyMenu\Debug\moc\moc_PonyMenu.cpp
; Line 68
	push	ebp
	mov	ebp, esp
; Line 66
	mov	eax, DWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@PonyMenu@@2UQMetaObject@@B, eax
	mov	DWORD PTR ?staticMetaObject@PonyMenu@@2UQMetaObject@@B+4, OFFSET ?qt_meta_stringdata_PonyMenu@@3Uqt_meta_stringdata_PonyMenu_t@@B
; Line 67
	mov	DWORD PTR ?staticMetaObject@PonyMenu@@2UQMetaObject@@B+8, OFFSET ?qt_meta_data_PonyMenu@@3QBIB
	mov	DWORD PTR ?staticMetaObject@PonyMenu@@2UQMetaObject@@B+12, OFFSET ?qt_static_metacall@PonyMenu@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; PonyMenu::qt_static_metacall
	mov	DWORD PTR ?staticMetaObject@PonyMenu@@2UQMetaObject@@B+16, 0
	mov	DWORD PTR ?staticMetaObject@PonyMenu@@2UQMetaObject@@B+20, 0
	pop	ebp
	ret	0
??__E?staticMetaObject@PonyMenu@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'PonyMenu::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@PonyMenu@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; PonyMenu::qt_static_metacall
; File C:\Users\t_bal\source\repos\PonyMenu\PonyMenu\Debug\moc\moc_PonyMenu.cpp
; Line 58
	push	ebp
	mov	ebp, esp
; Line 63
	pop	ebp
	ret	0
?qt_static_metacall@PonyMenu@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; PonyMenu::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@PonyMenu@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; PonyMenu::qt_metacall
; _this$ = ecx
; File C:\Users\t_bal\source\repos\PonyMenu\PonyMenu\Debug\moc\moc_PonyMenu.cpp
; Line 85
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 86
	mov	eax, DWORD PTR __a$[ebp]
	push	eax
	mov	ecx, DWORD PTR __id$[ebp]
	push	ecx
	mov	edx, DWORD PTR __c$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacall@QMainWindow@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	DWORD PTR __id$[ebp], eax
; Line 87
	mov	eax, DWORD PTR __id$[ebp]
; Line 88
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@PonyMenu@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; PonyMenu::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__clname$ = 8						; size = 4
?qt_metacast@PonyMenu@@UAEPAXPBD@Z PROC			; PonyMenu::qt_metacast
; _this$ = ecx
; File C:\Users\t_bal\source\repos\PonyMenu\PonyMenu\Debug\moc\moc_PonyMenu.cpp
; Line 77
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 78
	cmp	DWORD PTR __clname$[ebp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 79
	push	OFFSET ?qt_meta_stringdata_PonyMenu@@3Uqt_meta_stringdata_PonyMenu_t@@B+16
	mov	eax, DWORD PTR __clname$[ebp]
	push	eax
	call	_strcmp
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 80
	mov	eax, DWORD PTR _this$[ebp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 81
	mov	ecx, DWORD PTR __clname$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacast@QMainWindow@@UAEPAXPBD@Z
$LN1@qt_metacas:
; Line 82
	mov	esp, ebp
	pop	ebp
	ret	4
?qt_metacast@PonyMenu@@UAEPAXPBD@Z ENDP			; PonyMenu::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = -8						; size = 4
_this$ = -4						; size = 4
?metaObject@PonyMenu@@UBEPBUQMetaObject@@XZ PROC	; PonyMenu::metaObject
; _this$ = ecx
; File C:\Users\t_bal\source\repos\PonyMenu\PonyMenu\Debug\moc\moc_PonyMenu.cpp
; Line 72
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _this$[ebp], ecx
; Line 73
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	DWORD PTR [eax+24], 0
	je	SHORT $LN3@metaObject
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	ecx, eax
	call	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
	mov	DWORD PTR tv82[ebp], eax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	mov	DWORD PTR tv82[ebp], OFFSET ?staticMetaObject@PonyMenu@@2UQMetaObject@@B ; PonyMenu::staticMetaObject
$LN4@metaObject:
	mov	eax, DWORD PTR tv82[ebp]
; Line 74
	mov	esp, ebp
	pop	ebp
	ret	0
?metaObject@PonyMenu@@UBEPBUQMetaObject@@XZ ENDP	; PonyMenu::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File C:\qt\5.11.3\msvc2015\include\QtCore\qscopedpointer.h
; Line 117
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 118
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax]
; Line 119
	mov	esp, ebp
	pop	ebp
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\t_bal\source\repos\PonyMenu\PonyMenu\Debug\moc\moc_PonyMenu.cpp
; Line 91
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\t_bal\source\repos\PonyMenu\PonyMenu\Debug\moc\moc_PonyMenu.cpp
; Line 91
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
